### ISSUE TITLE
limitCount没有增加

### ISSUE THREAD

**Issue by aitxiaogang** [hanyunpeng0521/floor-drain-spring-boot-starter#1]
首先说声谢谢，这个框架对我来说很有用。
使用过程中遇到了两个问题

1. 不知道是不是我使用的方式不对，limitCount次数没有增加。
2. 怎么配置使用Redis来存储，我看设置中只能设置普通的属性

**Comment by pingxin403** [comment]
limitCount是当请求被限制时该值不为0，表示为被限制的次数
Redis模式需要应用配置redis连接即可，type改为Redis。

**Comment by aitxiaogang** [comment]
感谢回复，limitCount是需要我自己在拦截的时候重新设置该值还是框架自动递增该值呢。已经配置了redis链接，在配置文件中没有出现可以配置type的提示，我想type的那个枚举是不是要设置为静态内部类才能配置呢
